ALTER TABLE users ADD COLUMN points INT NOT NULL DEFAULT 0;

CREATE TABLE point_log (
  user_id INT NOT NULL,
  delta INT NOT NULL,
  reason VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
