ALTER TABLE users ADD COLUMN points INTEGER NOT NULL DEFAULT 0;

CREATE TABLE point_log (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  delta INTEGER NOT NULL,
  reason TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
